// Generated by Supabase CLI - DO NOT EDIT
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          name: string | null
          company_name: string | null
          subscription_tier: 'free' | 'pro' | 'team'
          stripe_customer_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          name?: string | null
          company_name?: string | null
          subscription_tier?: 'free' | 'pro' | 'team'
          stripe_customer_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string | null
          company_name?: string | null
          subscription_tier?: 'free' | 'pro' | 'team'
          stripe_customer_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          user_id: string
          name: string
          project_type: string | null
          contract_value: string | null
          start_date: string | null
          estimated_completion: string | null
          owner: string | null
          contractor: string | null
          architect: string | null
          description: string | null
          tags: string[] | null
          contract_file_url: string | null
          contract_text: string | null
          status: 'draft' | 'uploaded' | 'processing' | 'reviewed' | 'complete'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          project_type?: string | null
          contract_value?: string | null
          start_date?: string | null
          estimated_completion?: string | null
          owner?: string | null
          contractor?: string | null
          architect?: string | null
          description?: string | null
          tags?: string[] | null
          contract_file_url?: string | null
          contract_text?: string | null
          status?: 'draft' | 'uploaded' | 'processing' | 'reviewed' | 'complete'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          project_type?: string | null
          contract_value?: string | null
          start_date?: string | null
          estimated_completion?: string | null
          owner?: string | null
          contractor?: string | null
          architect?: string | null
          description?: string | null
          tags?: string[] | null
          contract_file_url?: string | null
          contract_text?: string | null
          status?: 'draft' | 'uploaded' | 'processing' | 'reviewed' | 'complete'
          created_at?: string
          updated_at?: string
        }
      }
      pay_applications: {
        Row: {
          id: string
          user_id: string
          status: 'draft' | 'finalized' | 'corrected-draft'
          entry_mode: 'guided' | 'from-previous' | 'blank'
          project_name: string
          owner_name: string
          contractor_name: string
          application_number: string
          period_start_date: string | null
          period_end_date: string | null
          payment_due_date: string | null
          billing_format: 'schedule-of-values' | 'total-only'
          materials_stored_enabled: boolean
          retainage_percent: string
          retainage_applies_to: 'work' | 'materials' | 'both'
          retainage_can_change: boolean
          retainage_effective_date: string | null
          retainage_new_percent: string | null
          change_orders_enabled: boolean
          change_order_mode: 'none' | 'totals-only' | 'individual'
          change_order_total_amount: string | null
          current_step: number
          completed_steps: number[]
          signer_name: string | null
          signer_title: string | null
          signature_date: string | null
          signature_notes: string | null
          corrected_from_id: string | null
          correction_reason: string | null
          correction_notes: string | null
          finalized_snapshot: Json | null
          finalized_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          status?: 'draft' | 'finalized' | 'corrected-draft'
          entry_mode: 'guided' | 'from-previous' | 'blank'
          project_name: string
          owner_name: string
          contractor_name: string
          application_number: string
          period_start_date?: string | null
          period_end_date?: string | null
          payment_due_date?: string | null
          billing_format: 'schedule-of-values' | 'total-only'
          materials_stored_enabled?: boolean
          retainage_percent?: string
          retainage_applies_to?: 'work' | 'materials' | 'both'
          retainage_can_change?: boolean
          retainage_effective_date?: string | null
          retainage_new_percent?: string | null
          change_orders_enabled?: boolean
          change_order_mode?: 'none' | 'totals-only' | 'individual'
          change_order_total_amount?: string | null
          current_step?: number
          completed_steps?: number[]
          signer_name?: string | null
          signer_title?: string | null
          signature_date?: string | null
          signature_notes?: string | null
          corrected_from_id?: string | null
          correction_reason?: string | null
          correction_notes?: string | null
          finalized_snapshot?: Json | null
          finalized_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          status?: 'draft' | 'finalized' | 'corrected-draft'
          entry_mode?: 'guided' | 'from-previous' | 'blank'
          project_name?: string
          owner_name?: string
          contractor_name?: string
          application_number?: string
          period_start_date?: string | null
          period_end_date?: string | null
          payment_due_date?: string | null
          billing_format?: 'schedule-of-values' | 'total-only'
          materials_stored_enabled?: boolean
          retainage_percent?: string
          retainage_applies_to?: 'work' | 'materials' | 'both'
          retainage_can_change?: boolean
          retainage_effective_date?: string | null
          retainage_new_percent?: string | null
          change_orders_enabled?: boolean
          change_order_mode?: 'none' | 'totals-only' | 'individual'
          change_order_total_amount?: string | null
          current_step?: number
          completed_steps?: number[]
          signer_name?: string | null
          signer_title?: string | null
          signature_date?: string | null
          signature_notes?: string | null
          corrected_from_id?: string | null
          correction_reason?: string | null
          correction_notes?: string | null
          finalized_snapshot?: Json | null
          finalized_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      pay_application_line_items: {
        Row: {
          id: string
          pay_application_id: string
          sort_order: number
          line_number: string
          description: string
          scheduled_value: string
          previous_work: string
          this_period_work: string
          previous_materials_stored: string
          this_period_materials_stored: string
          work_to_date: string
          materials_to_date: string
          earned_to_date: string
          balance_to_finish: string
          is_change_order_related: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          pay_application_id: string
          sort_order?: number
          line_number: string
          description: string
          scheduled_value?: string
          previous_work?: string
          this_period_work?: string
          previous_materials_stored?: string
          this_period_materials_stored?: string
          is_change_order_related?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          pay_application_id?: string
          sort_order?: number
          line_number?: string
          description?: string
          scheduled_value?: string
          previous_work?: string
          this_period_work?: string
          previous_materials_stored?: string
          this_period_materials_stored?: string
          work_to_date?: string
          materials_to_date?: string
          earned_to_date?: string
          balance_to_finish?: string
          is_change_order_related?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      pay_application_change_orders: {
        Row: {
          id: string
          pay_application_id: string
          co_number: string
          description: string
          amount: string
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          pay_application_id: string
          co_number: string
          description: string
          amount?: string
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          pay_application_id?: string
          co_number?: string
          description?: string
          amount?: string
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
      }
      extracted_terms: {
        Row: {
          id: string
          project_id: string
          category: 'contract_basics' | 'payment_terms' | 'retainage' | 'milestones' | 'insurance' | 'lien_waivers' | 'change_orders'
          field_name: string
          extracted_value: Json
          confidence_score: number
          source_location: string | null
          user_override: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          category: 'contract_basics' | 'payment_terms' | 'retainage' | 'milestones' | 'insurance' | 'lien_waivers' | 'change_orders'
          field_name: string
          extracted_value: Json
          confidence_score?: number
          source_location?: string | null
          user_override?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          category?: 'contract_basics' | 'payment_terms' | 'retainage' | 'milestones' | 'insurance' | 'lien_waivers' | 'change_orders'
          field_name?: string
          extracted_value?: Json
          confidence_score?: number
          source_location?: string | null
          user_override?: Json | null
          created_at?: string
        }
      }
      payment_schedules: {
        Row: {
          id: string
          project_id: string
          version: number
          schedule_data: Json
          total_contract_sum: string
          total_retainage: string
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          version?: number
          schedule_data: Json
          total_contract_sum: string
          total_retainage: string
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          version?: number
          schedule_data?: Json
          total_contract_sum?: string
          total_retainage?: string
          is_active?: boolean
          created_at?: string
        }
      }
      compliance_flags: {
        Row: {
          id: string
          project_id: string
          severity: 'high' | 'medium' | 'low'
          category: string
          title: string
          description: string | null
          recommendation: string | null
          source_clause: string | null
          is_resolved: boolean
          resolved_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          severity: 'high' | 'medium' | 'low'
          category: string
          title: string
          description?: string | null
          recommendation?: string | null
          source_clause?: string | null
          is_resolved?: boolean
          resolved_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          severity?: 'high' | 'medium' | 'low'
          category?: string
          title?: string
          description?: string | null
          recommendation?: string | null
          source_clause?: string | null
          is_resolved?: boolean
          resolved_at?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
