// Generated by Supabase CLI - DO NOT EDIT
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          name: string | null
          company_name: string | null
          subscription_tier: 'free' | 'pro' | 'team'
          stripe_customer_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          name?: string | null
          company_name?: string | null
          subscription_tier?: 'free' | 'pro' | 'team'
          stripe_customer_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string | null
          company_name?: string | null
          subscription_tier?: 'free' | 'pro' | 'team'
          stripe_customer_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          user_id: string
          name: string
          contract_file_url: string | null
          contract_text: string | null
          status: 'uploaded' | 'processing' | 'reviewed' | 'complete'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          contract_file_url?: string | null
          contract_text?: string | null
          status?: 'uploaded' | 'processing' | 'reviewed' | 'complete'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          contract_file_url?: string | null
          contract_text?: string | null
          status?: 'uploaded' | 'processing' | 'reviewed' | 'complete'
          created_at?: string
          updated_at?: string
        }
      }
      extracted_terms: {
        Row: {
          id: string
          project_id: string
          category: 'contract_basics' | 'payment_terms' | 'retainage' | 'milestones' | 'insurance' | 'lien_waivers' | 'change_orders'
          field_name: string
          extracted_value: Json
          confidence_score: number
          source_location: string | null
          user_override: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          category: 'contract_basics' | 'payment_terms' | 'retainage' | 'milestones' | 'insurance' | 'lien_waivers' | 'change_orders'
          field_name: string
          extracted_value: Json
          confidence_score?: number
          source_location?: string | null
          user_override?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          category?: 'contract_basics' | 'payment_terms' | 'retainage' | 'milestones' | 'insurance' | 'lien_waivers' | 'change_orders'
          field_name?: string
          extracted_value?: Json
          confidence_score?: number
          source_location?: string | null
          user_override?: Json | null
          created_at?: string
        }
      }
      payment_schedules: {
        Row: {
          id: string
          project_id: string
          version: number
          schedule_data: Json
          total_contract_sum: string
          total_retainage: string
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          version?: number
          schedule_data: Json
          total_contract_sum: string
          total_retainage: string
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          version?: number
          schedule_data?: Json
          total_contract_sum?: string
          total_retainage?: string
          is_active?: boolean
          created_at?: string
        }
      }
      compliance_flags: {
        Row: {
          id: string
          project_id: string
          severity: 'high' | 'medium' | 'low'
          category: string
          title: string
          description: string | null
          recommendation: string | null
          source_clause: string | null
          is_resolved: boolean
          resolved_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          severity: 'high' | 'medium' | 'low'
          category: string
          title: string
          description?: string | null
          recommendation?: string | null
          source_clause?: string | null
          is_resolved?: boolean
          resolved_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          severity?: 'high' | 'medium' | 'low'
          category?: string
          title?: string
          description?: string | null
          recommendation?: string | null
          source_clause?: string | null
          is_resolved?: boolean
          resolved_at?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
